### ISSUE TITLE
Row Detail with virtual scroll

### ISSUE THREAD

**Issue by java2kus** [swimlane/angular2-data-table#100]
I have a requirement to show the details of the row on click of the 'icon-right' icon.  I found the following in the source code but there are a lot of missing pieces on how to put the detail in the template.

https://github.com/swimlane/angular2-data-table/blob/master/src/demos/details.ts

I can keep the detail element height fixed so that it can help with the calculation of the virtual scroll bar.   Can you please let me know if this is possible with the current version of the component?

Thanks!

**Comment by amcdnl** [comment]
I started tinkering with this but have not went very far yet. I do plan to eventually implement but won't have time in the near future. If you are interested, I'm happy to point you in the right direction to address.

**Comment by java2kus** [comment]
@amcdnl Yes I am interested.   Can you please give me some pointers around this?  I will give it a shot.

**Comment by amcdnl** [comment]
@java2kus Awesome; heres my thoughts...

- Add a new component like `RowDetail` to the `Body` component. I did something like this in the preview component for row grouping; see: https://github.com/swimlane/angular-data-table/blob/master/src/components/body/BodyDirective.js#L33
- The new component should span all columns, which might get odd with column pinning. Open to ideas on this though.
- We don't want to make the +/- buttons hard coded, instead we should probably demonstrate how to trigger a event / function to toggle this.
- When the detail is expanded you will need to update the scroller and the pagination to reflect the additional new height ( current row count * height + detail height * num of details opened ). https://github.com/swimlane/angular2-data-table/blob/master/src/directives/Scroller.ts#L34
- Next you will also need to update the row translate positions to accomodate for your new height; this is done here: https://github.com/swimlane/angular2-data-table/blob/master/src/components/body/Body.ts#L170
- Add a new option in the `TableOptions` for detail row height. This will have to be fixed if you plan to use virtual scrolling, otherwise, its not really needed.

Thats it ( LOL ). When you have a PR, let me know and I can review.

**Comment by java2kus** [comment]
#201

**Comment by Phota16** [comment]
if I do the row-details(ngx-datatable/demo/basic/row-detail.ts) code directly in  the app.component it worked fine(without routing). But if I have load the row-details component inside <router-outlet> then  click on  icon('>') on the row to expand it  won’t open it just refresh the page.

any help is greatly appreciated
thank you

**Comment by Phota16** [comment]
Open the row details demo, expand 2 row by click on the left arrow image, then scroll down and up.
Close the expanded row see the rows are missing from the table. If you will scroll again then the missing row loaded.
![image](https://cloud.githubusercontent.com/assets/20189130/23667425/68db3716-0323-11e7-975b-dc21509fbfdb.png)

**Comment by PrashantBisht** [comment]
yup same issue encountered when i expand the rows are getting hidden.
