### ISSUE TITLE
Sorting should be handled on server side

### ISSUE THREAD

**Issue by jntakpe** [swimlane/angular2-data-table#170]
**I'm submitting a ...** 

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When using external paging, when clicking column header pagination is triggered on client side.

**Expected behavior**
When external paging is active, sorting operations should be executed on server side

**Reproduction of the problem**
https://swimlane.gitbooks.io/angular2-data-table/content/examples/server-paging.html
Change page => company.json is called
Change sort => no server calls

**What is the motivation / use case for changing the behavior?**
Having accurate displayed data

**Comment by amcdnl** [comment]
I'm simulating a server call, there is no data loaded into the table except whats in view.

**Comment by jntakpe** [comment]
I do understand that. I mean when sorting data from server there is no calls too and IMO its a bug.
The client side should not sort data because when external paging is activated only the server should be able to sort data.
My workaround is to listen to onColumnChange event and then call server with sorting infos then update table.

**Comment by amcdnl** [comment]
You add a hook to the column comparator to sort on server. I do see your point, its a tad odd given this. Maybe we have a warning if that combo is done?

**Comment by jntakpe** [comment]
I'm just listening to onColumnChange event like that : 
`
<datatable [rows]="myRows" [options]="dtOptions" (onPageChange)="changePage()"
           (onColumnChange)="sortColumn()">
</datatable>
`
When the column header is clicked, sortColumn function is called to update rows on server side.
I'm not using the TableColumn's comparator property.

I guess a warning is fine.

**Comment by tsquillario** [comment]
Just ran into this issue. To disable client-side sorting I had to bind the column's comparator to an empty function. Using onColumnChange and filtering it for 'sort' events works for me!

Might want to add a TableOption for externalSorting or combine it with externalPaging since they would be used together in most situations.

Working on a new Angular2 project, this data-table is working well so far!

**Comment by fridolin-koch** [comment]
+1 for externalSorting

**Comment by amcdnl** [comment]
Ya, I was kinda torn on this. 

So in 1.0 I made it where if you pass a falsey, it will not use the compare fn. This allows u to use client side for some columns and server sorting for others at the same time.  In hind sight,  I'm not sure how useful that actually is but seemed like good idea at time. My goal was to try to make as minimal and implicit api as possible.

I do agree it can be confusing and since we already have external paging flag ill fold and add this too.

**Comment by amcdnl** [comment]
Fixed in latest. Use `externalSorting` prop.
