### ISSUE TITLE
Only one row visible at init with scrollbarV

### ISSUE THREAD

**Issue by ocombe** [swimlane/angular2-data-table#241]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When you set the option scrollbarV to true, and add a few rows at init of the table, only 1 row is visible instead of all your rows. Whenever you scroll (horizontally or vertically) it shows the correct number of rows

**Expected behavior**
It should show all visible rows at init

**Reproduction of the problem**
http://plnkr.co/edit/bGk5ZbAwcjYhPb2gDNfo?p=preview
I added 6 rows but only 1 is visible at init. To make the other appear use the horizontal scrollbar in the table and they should pop. (It also works with vertical scrollbars).

* **Table version:** 0.12.0

* **Angular version:** 2.1.2

* **Browser:** all

**Comment by ocombe** [comment]
Fixed in 1.0.0, thanks !

**Comment by lagofvc** [comment]
I had a somewhat similar issue using scrollbarV except it wasn't only on init and the table never showed more than 1 row.   I put this on my component's css and fixed the issue: 

`.datatable { height: 800px; }`

In case it helps anyone else.  
Thank you!

**Comment by amcdnl** [comment]
Ya, if you are doing virtual scrolling, we kinda gotta have a height to measure against.

**Comment by Pietsen** [comment]
i have the same issue like @lagofvc but his solution won't work on my table. Any further suggestions for solving the problem? 

If i deactivate [scrollbarV]="true", the table is shown correctly, but i don't want the page to be scrolled. Instead i want to add [scrollbarV]="true" but then the table shows only the first row(!) and that is strange because if i filter something or sort it the first row is changing.

Hope you guys can help me.

**Comment by GrimaceOfDespair** [comment]
I'm having the same issue: table works properly without scrollbarV, but with, it shows only 1 line. The scroll does seem to work, though, including paging as if page size is effectively 1.

- **Table version:** 11.3.0

- **Angular version:** 5.2.10

- **Browser:** Chrome 71.0.3578.98
