### ISSUE TITLE
Permanently high CPU utilization after sorting

### ISSUE THREAD

**Issue by Thoma5** [swimlane/angular2-data-table#359]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Permanently high cpu utilization after sorting. The utilization will stay high till the tab is reloaded. Also after another sort the cpu utilization will increase permanently (up to 100%).
**Expected behavior**
After sorting the cpu utilization should go down to <10%.

**Reproduction of the problem**
Reproducible in your demo, just click sort in the demo, wait a bit or click a bit around. The cpu utilization will remain on a high level.

**What is the motivation / use case for changing the behavior?**
Lags after sorting

**Please tell us about your environment:**

Arch Linux 4.8.11
Chromium Version 55.0.2883.75 (64-bit)
Firefox Version 50.0.2
CPU: i5 2500k@ 4,4Ghz, 24GB of RAM
HW Acceleration enabled (Only Native GpuMemoryBuffers and Rasterization HW acceleratiion disabled)

* **Table version:** 2.2.0
Version in the current demo (2.2.0)

* **Angular version:** 2.3.0
Version in the current demo for version 2.2.0

**Comment by JanCejka** [comment]
Issue is probably in the code that adds & removes "sort-desc" / "icon-up" classes on span.sort-btn element. If you inspect this element, it looks like list of classes is "flickering". If you break on attributes modification of this span element, you would get pretty instant breaks where you see that these two classes are being removed and re-added very fast.

**Comment by amcdnl** [comment]
Thanks for details! My thought was that it might been related to debug mode but if the site is doing it too then ya.

**Comment by JanCejka** [comment]
So based on my tracking I believe problem is in `sortClasses` function of `DataTableHeaderCellComponent`. 
```typescript
sortClasses(dir: SortDirection): any {
    let result = {};

    if(dir === SortDirection.asc) {
      result[`sort-asc ${this.sortAscendingIcon}`] = true;
    } else if(dir === SortDirection.desc) {
      result[`sort-desc ${this.sortDescendingIcon}`] = true;
    }

    return result;
  }
```
It returns every time new object (`let result = {};`). And since this is object and not string, Angular change detection believes that object has changed (Angular compares object references, not deep comparison via object attributes):

```javascript
function looseIdentical(a, b) {
    return a === b || typeof a === 'number' && typeof b === 'number' && isNaN(a) && isNaN(b);
}
```
And as a result of this detected change, angular sets "new" ngClass:
```javascript
    Object.defineProperty(NgClass.prototype, "ngClass", {
        set: function (v) {
            this._cleanupClasses(this._rawClass);
            this._iterableDiffer = null;
            this._keyValueDiffer = null;
```
Flickering (and on top CPU load) is caused by cleanupClasses call. First it cleans old `sort-asc` and `icon-down` classes and immediately then it re-creates them. Since sorting changes only after header is clicked, I would recommend creating object permanently as a private property of component and re-create it only on sorting change instead of creating new object on every function call. I believe this would solve the issue. Or returning pure string instead of Object should work as well. Still, immutable object should be better for performance reasons (you would compare references, not values).

**Comment by amcdnl** [comment]
Ah, I can fix this easily. Thanks for tracking it down.

**Comment by amcdnl** [comment]
Fixed. Please pull latest in a few to retry.

**Comment by Thoma5** [comment]
Thanks, works fine now!
